### ISSUE TITLE
"Display As..." does not seem to work

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-cloud-public#105]
![image](https://user-images.githubusercontent.com/5834130/75073733-ea4a4500-54ae-11ea-8402-454f149fc483.png)
Having something like the above, and I right click and select "Display As..." and select anything, I get the little spinning wheel up at the top, but it just hangs indefinitely and never chances the display of the operand.

**Comment by negasora** [comment]
Fixed in 1.0.680
