### ISSUE TITLE
Change type doesn't work in data sections

### ISSUE THREAD

**Issue by meithecatte** [Vector35/binaryninja-cloud-public#121]
```
~/tmp$ cat hello.c
#include <stdio.h>
int main() { puts("Hello, world!"); }
~/tmp$ gcc hello.c -o hello
~/tmp$ # Binary attached
```

1. Create a session with [the attached file](https://github.com/Vector35/binaryninja-cloud-public/files/4630111/hello.gz)
2. Switch to the fifth tab. The tooltip says "Types", but I doubt that's what the tab is called.
3. Doubleclick on the starting address of the `.init_array` section.
4. Rightclick on the `__init_array_start` label and choose "Change Type"
5. In the input field, change void to void*
6. Click Submit and observe the "Command failure" popup in the top right.

This is not the only label where it happens, see `_IO_stdin_used` and try changing it to a `uint8_t`, for example. Also happens when I try to create a variable by clicking on a byte, pressing `y` and typing `char foo[4]`.

I can reproduce this on both Firefox 68 and Chromium 81.

**Comment by negasora** [comment]
Fixed in 1.0.773
