### ISSUE TITLE
"Display as" doesn't work in the linear disassembly view

### ISSUE THREAD

**Issue by meithecatte** [Vector35/binaryninja-cloud-public#122]
```
~/tmp$ cat hello.c
#include <stdio.h>
int main() { puts("Hello, world!"); }
~/tmp$ gcc hello.c -o hello
~/tmp$ # Binary attached
```

1. Create a session with [the attached file](https://github.com/Vector35/binaryninja-cloud-public/files/4630111/hello.gz)
2. Click on the code of `_start` being shown to obtain focus (should this be necessary?)
3. Press space to switch to linear disassembly view
4. Doubleclick on `main`
5. In the `mov edi, 0x402004` instruction, right click and choose 'display as -> binary'. The view will reload with the instruction still being shown in hex.

In other situations which I can't seem to reproduce right now, the response was a "Command failed" popup in the upper right corner of the screen.

**Comment by negasora** [comment]
Fixed in 1.0.751
