### ISSUE TITLE
Keyboard Shortcuts don't work in many situations

### ISSUE THREAD

**Issue by ConnorNelson** [Vector35/binaryninja-cloud-public#126]
I've enjoyed using binary ninja cloud over the last several months for basic reverse engineering (looking at CTF challenges). It's really convenient to have access to this tool in the browser, so thanks.

By far my biggest issue with binary ninja cloud over the last several months has been the keyboard shortcuts. The shortcuts just don't do anything in a number of situations. This adds a lot of friction.

The simplest example I can provide is using space to toggle between linear and graph view. If I am in graph view (active element div#Disassembly_View.container-fluid) and hit space, it will bring me to linear view (active element div#Analysis_Wrapper). But hitting space again will not return me to graph view. Instead I must click on the top bar (div.appContainer), and then click back on the linear view (div#Analysis_Wrapper), and then hitting space will return me to graph view (probably incorrectly, div#Analysis_Wrapper is still the active element). Again, if I must repeat the process of clicking the top bar and then back on the graph view in order to return to linear view.

As another example, if I switch outside of my browser and then back in, "g" will work. But then if I hit space to change views, "g" is just broken until I unfocus from my browser.

This friction of the keyboard shortcuts not working smoothly makes them basically unusable for me, which is unfortunate.

It would be awesome if the keyboard shortcuts just worked from any context of the program.

Thanks.

**Comment by negasora** [comment]
Glad you've enjoyed using it outside of the hotkey hiccups. I just pushed a ton of improvements, fixing the issues listed here. Let me know if you run in to any more cases!

Fixed in 1.0.773

**Comment by ConnorNelson** [comment]
Great, this works much better. Thanks!
