### ISSUE TITLE
Function List UI Quirks

### ISSUE THREAD

**Issue by xavierholt** [Vector35/binaryninja-cloud-public#133]
I wanted to record a couple UI quirks I noticed with the function list.  I'm running Firefox 78.0.2 on OS X 10.15.5.

- The function filter (search by name) is hidden by default.  This a super useful feature, but I never would have known it existed if I hadn't tabbed into it by accident.  A permanent text input for this would be nice to have.

- In most cases, double clicking function names in the list jumps the view to that function.  But double clicking the currently active function name does nothing.  I'd prefer that it had the same behavior - it would be very useful to get back to the default view of your current function after scrolling / zooming away.

- And finally, very minor:  The last function name clicked is highlighted in bright blue.  This is very noticeable, but doesn't seem to have any effect on anything (maybe I'm missing something?).  Meanwhile, the currently active function, which does control the behavior of the UI (it's the function that will be focused when switching views) gets much subtler blue text.

<img width="453" alt="Screen Shot 2020-08-18 at 1 38 36 PM" src="https://user-images.githubusercontent.com/1435765/90564540-64a40b00-e15a-11ea-9c72-4df6cd5ff81e.png">

**Comment by negasora** [comment]
The first two issues are fixed in 1.0.780
The last point can be fixed by changing your user theme (user dropdown > modify theme)

**Comment by xavierholt** [comment]
That was super fast - thanks a ton!
