### ISSUE TITLE
Goto Address does not focus and Enter fails

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-cloud-public#50]
When hitting `G` to go to an address, I have to click on the text box in order to start entering the address and click on `Go` / `Cancel` after I am done entering the address. It would be nice if , similar to renaming a function, the focus would be on the text box and pressing `enter` and `escape` would `go` or `cancel` respectively. 

On a side note.. the `Go` button makes sense for `Go to address` but not so much for renaming a function.

**Comment by negasora** [comment]
closing and referencing #8 so this can be fixed on implementation
